create table public.contest_results (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 80),
  wpm integer not null default 0,
  accuracy integer not null default 0 check (accuracy between 0 and 100),
  score integer not null default 0,
  time text not null default '',
  date text not null default '',
  elapsed_ms bigint not null default 0,
  errors integer not null default 0,
  completed boolean not null default false
);

alter table public.contest_results enable row level security;
grant select, insert on public.contest_results to anon;
grant usage, select on sequence public.contest_results_id_seq to anon;

create policy "Anyone can view contest results"
  on public.contest_results for select to anon using (true);

create policy "Anyone can submit contest results"
  on public.contest_results for insert to anon with check (true);